Guard against search-path-based attacks
pgaudit/pgaudit pull request #156
Opened 2021-09-08 12:13 UTC by shinderuk

Use qualified references to functions and operators in the SQL queries
executed in the event triggers.

Here is a demo of the vulnerability:
```
create function upper(text) returns text language sql as 'select (1/0)::text';
create function lower(text) returns text language sql as 'select (1/0)::text';
create function my_ne(text, text) returns bool language sql as 'select (1/0)::bool';
create operator <> (function = my_ne, leftarg = text, rightarg = text);

set search_path = public, pg_catalog;

create table t (); -- fails without the patch
drop table t; -- fails without the patch
```

2021-09-08 16:11 UTC, dwsteele requested changes
These changes look good to me. Can you integrate your example into the regression tests?

2021-09-08 19:46 UTC, shinderuk commented
I added the test, but doubt if it's really useful. I can easily imagine adding another unqualified function or operator to the query without failing the test. Not to mention something subtle like an IN expression. But at least it will fail if one reverts the change :)

BTW, I would rather call this a bug, not an enhancement, because one can bypass logging.

2021-09-08 21:12 UTC, dwsteele commented
> But at least it will fail if one reverts the change :)

Yes, and also nice for doing before/after comparisons of the fix.

> BTW, I would rather call this a bug, not an enhancement, because one can bypass logging.

Agreed, that was my bad. And being a bug means we can backpatch.

2021-11-02 17:12 UTC, dwsteele approved these changes

2021-11-04 13:20 UTC, sfrost approved these changes

2021-11-04 15:21 UTC, merged